---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go test -v -cover ./...

- name: build
  pull: default
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - sh .drone.sh

- name: publish
  image: plugins/docker
  settings:
    repo: viant/drone-autoscaler
    username: replicant0wnz 
    password:
      from_secret: docker_password
    tags:
      - latest
      - 1.0.${DRONE_BUILD_NUMBER}

volumes:
- name: deps
  temp: {}
